apiVersion: v1
kind: Service
metadata:
  name: "{{Name}}"
  labels:
    droidherdId: "{{Name}}"
    droidherdSessionName: "{{DroidherdSessionName}}"
    droidherdClientId: "{{ClientId}}"
    droidherdSessionId: "{{SessionId}}"
    image: "{{Image}}"
  ownerReferences:
    - apiVersion: testops.tinkoff.ru/v1
      kind: DroidherdSession
      name: "{{DroidherdSessionName}}"
      uid: "{{UID}}"
      blockOwnerDeletion: false
spec:
  selector:
    droidherdId: "{{Name}}"
    droidherdSessionName: "{{DroidherdSessionName}}"
  type: NodePort
  ports:
    - name: tcp-adb
      port: 5555
      protocol: TCP
