restartPolicy: Always

strategy:
  type: "RollingUpdate"
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

app:
  host: ''
  shortHost: ''
  component: "emulator"
  replicaCount: 1
  image:
    name: localhost:5000/droidherd-service
    tag: local
    pullPolicy: "Always"
  service:
    port: 8080
    systemPort: 8085
  resources:
    limits:
      memory: 512Mb
      cpu: 0.5
  auth:
    superuser: "droidherd-default"

environment: test
