apiVersion: v1
kind: ConfigMap
metadata:
  name: droidherd-config
  labels:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
data:
  application.conf: |
{{ .Files.Get "config/application.conf" | indent 4 }}
  application.yaml: |
{{ .Files.Get "config/application.yaml" | indent 4 }}
  basic-auth.json: |
{{ .Files.Get "config/basic-auth.json" | indent 4 }}
  quotas.conf: |
{{ .Files.Get "config/quotas.conf" | indent 4 }}
  logback.xml: |
{{ .Files.Get "config/logback.xml" | indent 4 }}
