apiVersion: v1
kind: Service
metadata:
  name: {{ template "droidherd-service.name" . }}-internal
  labels:
    app: {{ template "droidherd-service.name" . }}
    service: {{ template "droidherd-service.name" . }}
    version: v1
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    app: {{ template "droidherd-service.name" . }}
    version: v1
  type: ClusterIP
  ports:
    - name: http-system
      port: {{ .Values.app.service.systemPort }}
