/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.tinkoff.testops.droidherd.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * DroidherdSessionStatus defines the observed state of DroidherdSession
 */
@ApiModel(description = "DroidherdSessionStatus defines the observed state of DroidherdSession")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-17T14:14:44.512Z[Etc/UTC]")
public class V1DroidherdSessionStatus {
  public static final String SERIALIZED_NAME_EMULATORS = "emulators";
  @SerializedName(SERIALIZED_NAME_EMULATORS)
  private List<V1DroidherdSessionStatusEmulators> emulators = new ArrayList<>();

  public static final String SERIALIZED_NAME_LAST_SEEN = "lastSeen";
  @SerializedName(SERIALIZED_NAME_LAST_SEEN)
  private String lastSeen;


  public V1DroidherdSessionStatus emulators(List<V1DroidherdSessionStatusEmulators> emulators) {

    this.emulators = emulators;
    return this;
  }

  public V1DroidherdSessionStatus addEmulatorsItem(V1DroidherdSessionStatusEmulators emulatorsItem) {
    this.emulators.add(emulatorsItem);
    return this;
  }

   /**
   * Allocated emulators
   * @return emulators
  **/
  @ApiModelProperty(required = true, value = "Allocated emulators")

  public List<V1DroidherdSessionStatusEmulators> getEmulators() {
    return emulators;
  }


  public void setEmulators(List<V1DroidherdSessionStatusEmulators> emulators) {
    this.emulators = emulators;
  }


  public V1DroidherdSessionStatus lastSeen(String lastSeen) {

    this.lastSeen = lastSeen;
    return this;
  }

   /**
   * Get lastSeen
   * @return lastSeen
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLastSeen() {
    return lastSeen;
  }


  public void setLastSeen(String lastSeen) {
    this.lastSeen = lastSeen;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1DroidherdSessionStatus v1DroidherdSessionStatus = (V1DroidherdSessionStatus) o;
    return Objects.equals(this.emulators, v1DroidherdSessionStatus.emulators) &&
        Objects.equals(this.lastSeen, v1DroidherdSessionStatus.lastSeen);
  }

  @Override
  public int hashCode() {
    return Objects.hash(emulators, lastSeen);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1DroidherdSessionStatus {\n");
    sb.append("    emulators: ").append(toIndentedString(emulators)).append("\n");
    sb.append("    lastSeen: ").append(toIndentedString(lastSeen)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

