/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.tinkoff.testops.droidherd.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * V1DroidherdSessionSpecClient
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-17T14:14:44.512Z[Etc/UTC]")
public class V1DroidherdSessionSpecClient {
  public static final String SERIALIZED_NAME_CI = "ci";
  @SerializedName(SERIALIZED_NAME_CI)
  private V1DroidherdSessionSpecClientCi ci;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_INFO = "info";
  @SerializedName(SERIALIZED_NAME_INFO)
  private String info;

  public static final String SERIALIZED_NAME_IP = "ip";
  @SerializedName(SERIALIZED_NAME_IP)
  private String ip;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private String version;


  public V1DroidherdSessionSpecClient ci(V1DroidherdSessionSpecClientCi ci) {

    this.ci = ci;
    return this;
  }

   /**
   * Get ci
   * @return ci
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1DroidherdSessionSpecClientCi getCi() {
    return ci;
  }


  public void setCi(V1DroidherdSessionSpecClientCi ci) {
    this.ci = ci;
  }


  public V1DroidherdSessionSpecClient id(String id) {

    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public V1DroidherdSessionSpecClient info(String info) {

    this.info = info;
    return this;
  }

   /**
   * Get info
   * @return info
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getInfo() {
    return info;
  }


  public void setInfo(String info) {
    this.info = info;
  }


  public V1DroidherdSessionSpecClient ip(String ip) {

    this.ip = ip;
    return this;
  }

   /**
   * Get ip
   * @return ip
  **/
  @ApiModelProperty(required = true, value = "")

  public String getIp() {
    return ip;
  }


  public void setIp(String ip) {
    this.ip = ip;
  }


  public V1DroidherdSessionSpecClient version(String version) {

    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(required = true, value = "")

  public String getVersion() {
    return version;
  }


  public void setVersion(String version) {
    this.version = version;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1DroidherdSessionSpecClient v1DroidherdSessionSpecClient = (V1DroidherdSessionSpecClient) o;
    return Objects.equals(this.ci, v1DroidherdSessionSpecClient.ci) &&
        Objects.equals(this.id, v1DroidherdSessionSpecClient.id) &&
        Objects.equals(this.info, v1DroidherdSessionSpecClient.info) &&
        Objects.equals(this.ip, v1DroidherdSessionSpecClient.ip) &&
        Objects.equals(this.version, v1DroidherdSessionSpecClient.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ci, id, info, ip, version);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1DroidherdSessionSpecClient {\n");
    sb.append("    ci: ").append(toIndentedString(ci)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    info: ").append(toIndentedString(info)).append("\n");
    sb.append("    ip: ").append(toIndentedString(ip)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

