/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.tinkoff.testops.droidherd.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * V1DroidherdSessionStatusEmulators
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-17T14:14:44.512Z[Etc/UTC]")
public class V1DroidherdSessionStatusEmulators {
  public static final String SERIALIZED_NAME_ADB = "adb";
  @SerializedName(SERIALIZED_NAME_ADB)
  private String adb;

  public static final String SERIALIZED_NAME_EXTRA_URIS = "extraUris";
  @SerializedName(SERIALIZED_NAME_EXTRA_URIS)
  private List<V1DroidherdSessionStatusExtraUris> extraUris = null;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_IMAGE = "image";
  @SerializedName(SERIALIZED_NAME_IMAGE)
  private String image;

  public static final String SERIALIZED_NAME_READY = "ready";
  @SerializedName(SERIALIZED_NAME_READY)
  private Boolean ready;


  public V1DroidherdSessionStatusEmulators adb(String adb) {

    this.adb = adb;
    return this;
  }

   /**
   * Get adb
   * @return adb
  **/
  @ApiModelProperty(required = true, value = "")

  public String getAdb() {
    return adb;
  }


  public void setAdb(String adb) {
    this.adb = adb;
  }


  public V1DroidherdSessionStatusEmulators extraUris(List<V1DroidherdSessionStatusExtraUris> extraUris) {

    this.extraUris = extraUris;
    return this;
  }

  public V1DroidherdSessionStatusEmulators addExtraUrisItem(V1DroidherdSessionStatusExtraUris extraUrisItem) {
    if (this.extraUris == null) {
      this.extraUris = new ArrayList<>();
    }
    this.extraUris.add(extraUrisItem);
    return this;
  }

   /**
   * Get extraUris
   * @return extraUris
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1DroidherdSessionStatusExtraUris> getExtraUris() {
    return extraUris;
  }


  public void setExtraUris(List<V1DroidherdSessionStatusExtraUris> extraUris) {
    this.extraUris = extraUris;
  }


  public V1DroidherdSessionStatusEmulators id(String id) {

    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public V1DroidherdSessionStatusEmulators image(String image) {

    this.image = image;
    return this;
  }

   /**
   * Get image
   * @return image
  **/
  @ApiModelProperty(required = true, value = "")

  public String getImage() {
    return image;
  }


  public void setImage(String image) {
    this.image = image;
  }


  public V1DroidherdSessionStatusEmulators ready(Boolean ready) {

    this.ready = ready;
    return this;
  }

   /**
   * Get ready
   * @return ready
  **/
  @ApiModelProperty(required = true, value = "")

  public Boolean getReady() {
    return ready;
  }


  public void setReady(Boolean ready) {
    this.ready = ready;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1DroidherdSessionStatusEmulators v1DroidherdSessionStatusEmulators = (V1DroidherdSessionStatusEmulators) o;
    return Objects.equals(this.adb, v1DroidherdSessionStatusEmulators.adb) &&
        Objects.equals(this.extraUris, v1DroidherdSessionStatusEmulators.extraUris) &&
        Objects.equals(this.id, v1DroidherdSessionStatusEmulators.id) &&
        Objects.equals(this.image, v1DroidherdSessionStatusEmulators.image) &&
        Objects.equals(this.ready, v1DroidherdSessionStatusEmulators.ready);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adb, extraUris, id, image, ready);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1DroidherdSessionStatusEmulators {\n");
    sb.append("    adb: ").append(toIndentedString(adb)).append("\n");
    sb.append("    extraUris: ").append(toIndentedString(extraUris)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    ready: ").append(toIndentedString(ready)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

