/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.tinkoff.testops.droidherd.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * DroidherdSessionSpec defines the desired state of DroidherdSession
 */
@ApiModel(description = "DroidherdSessionSpec defines the desired state of DroidherdSession")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-17T14:14:44.512Z[Etc/UTC]")
public class V1DroidherdSessionSpec {
  public static final String SERIALIZED_NAME_CLIENT = "client";
  @SerializedName(SERIALIZED_NAME_CLIENT)
  private V1DroidherdSessionSpecClient client;

  public static final String SERIALIZED_NAME_EMULATORS = "emulators";
  @SerializedName(SERIALIZED_NAME_EMULATORS)
  private List<V1DroidherdSessionSpecEmulators> emulators = new ArrayList<>();

  public static final String SERIALIZED_NAME_IS_DEBUG = "isDebug";
  @SerializedName(SERIALIZED_NAME_IS_DEBUG)
  private Boolean isDebug;

  public static final String SERIALIZED_NAME_PARAMETERS = "parameters";
  @SerializedName(SERIALIZED_NAME_PARAMETERS)
  private List<V1DroidherdSessionSpecParameters> parameters = null;

  public static final String SERIALIZED_NAME_SESSION_ID = "sessionId";
  @SerializedName(SERIALIZED_NAME_SESSION_ID)
  private String sessionId;


  public V1DroidherdSessionSpec client(V1DroidherdSessionSpecClient client) {

    this.client = client;
    return this;
  }

   /**
   * Get client
   * @return client
  **/
  @ApiModelProperty(required = true, value = "")

  public V1DroidherdSessionSpecClient getClient() {
    return client;
  }


  public void setClient(V1DroidherdSessionSpecClient client) {
    this.client = client;
  }


  public V1DroidherdSessionSpec emulators(List<V1DroidherdSessionSpecEmulators> emulators) {

    this.emulators = emulators;
    return this;
  }

  public V1DroidherdSessionSpec addEmulatorsItem(V1DroidherdSessionSpecEmulators emulatorsItem) {
    this.emulators.add(emulatorsItem);
    return this;
  }

   /**
   * Get emulators
   * @return emulators
  **/
  @ApiModelProperty(required = true, value = "")

  public List<V1DroidherdSessionSpecEmulators> getEmulators() {
    return emulators;
  }


  public void setEmulators(List<V1DroidherdSessionSpecEmulators> emulators) {
    this.emulators = emulators;
  }


  public V1DroidherdSessionSpec isDebug(Boolean isDebug) {

    this.isDebug = isDebug;
    return this;
  }

   /**
   * Get isDebug
   * @return isDebug
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsDebug() {
    return isDebug;
  }


  public void setIsDebug(Boolean isDebug) {
    this.isDebug = isDebug;
  }


  public V1DroidherdSessionSpec parameters(List<V1DroidherdSessionSpecParameters> parameters) {

    this.parameters = parameters;
    return this;
  }

  public V1DroidherdSessionSpec addParametersItem(V1DroidherdSessionSpecParameters parametersItem) {
    if (this.parameters == null) {
      this.parameters = new ArrayList<>();
    }
    this.parameters.add(parametersItem);
    return this;
  }

   /**
   * Get parameters
   * @return parameters
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1DroidherdSessionSpecParameters> getParameters() {
    return parameters;
  }


  public void setParameters(List<V1DroidherdSessionSpecParameters> parameters) {
    this.parameters = parameters;
  }


  public V1DroidherdSessionSpec sessionId(String sessionId) {

    this.sessionId = sessionId;
    return this;
  }

   /**
   * Get sessionId
   * @return sessionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSessionId() {
    return sessionId;
  }


  public void setSessionId(String sessionId) {
    this.sessionId = sessionId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1DroidherdSessionSpec v1DroidherdSessionSpec = (V1DroidherdSessionSpec) o;
    return Objects.equals(this.client, v1DroidherdSessionSpec.client) &&
        Objects.equals(this.emulators, v1DroidherdSessionSpec.emulators) &&
        Objects.equals(this.isDebug, v1DroidherdSessionSpec.isDebug) &&
        Objects.equals(this.parameters, v1DroidherdSessionSpec.parameters) &&
        Objects.equals(this.sessionId, v1DroidherdSessionSpec.sessionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(client, emulators, isDebug, parameters, sessionId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1DroidherdSessionSpec {\n");
    sb.append("    client: ").append(toIndentedString(client)).append("\n");
    sb.append("    emulators: ").append(toIndentedString(emulators)).append("\n");
    sb.append("    isDebug: ").append(toIndentedString(isDebug)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

