apiVersion: v1
kind: Pod
metadata:
  name: "{{Name}}"
  labels:
    droidherdId: "{{Name}}"
    droidherdSessionName: "{{DroidherdSessionName}}"
    droidherdClientId: "{{ClientId}}"
    droidherdSessionId: "{{SessionId}}"
    image: "{{Image}}"
  ownerReferences:
    - apiVersion: testops.tinkoff.ru/v1
      kind: DroidherdSession
      name: "{{DroidherdSessionName}}"
      uid: "{{UID}}"
      blockOwnerDeletion: false
spec:
  automountServiceAccountToken: false
  restartPolicy: Always
  containers:
    - name: "{{EmulatorContainerName}}"
      image: "{{FullQualifiedImage}}"
      securityContext:
        privileged: true
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /dev/kvm
          name: dev-kvm
        - mountPath: /dev/shm
          name: dev-shm
      ports:
        - containerPort: 5555
          name: tcp-adb
          protocol: TCP
      env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: EMULATOR_ARGS
          value: "{{EmulatorArgs}}"
        - name: EMULATOR_PROXY
          value: "{{EmulatorProxy}}"
        - name: EMULATOR_ID
          value: '{{Name}}'
        - name: CLIENT_ID
          value: '{{ClientId}}'
      readinessProbe:
        exec:
          command:
            - cat
            - /emulator.ready
        initialDelaySeconds: 60
        timeoutSeconds: 5
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 70
      resources:
        limits:
          cpu: "3"
        requests:
          memory: 6Gi
  volumes:
    - name: dev-kvm
      hostPath:
        path: /dev/kvm
    - name: dev-shm
      hostPath:
        path: /dev/shm
  terminationGracePeriodSeconds: 0
