name: Building, testing and assembling jar-file

on:
  push:
    branches: [ "main", "build-docker" ]
  pull_request:
  workflow_dispatch:

env:
  DOCKER_REPOSITORY: ${{secrets.DOCKER_REPOSITORY}}

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        run: echo "${{ secrets.DOCKER_REPOSITORY_PASSWORD }}" | docker login -u $DOCKER_REPOSITORY --password-stdin

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Build, test and assemble jar
        run: ./gradlew build test bootJar


      - name: Build Docker Image
        run: |
          docker build ./app --file ./app/OssDockerfile --tag $DOCKER_REPOSITORY/droidherd:latest

      - name: Push Image to Docker Hub
        run: |
          docker push $DOCKER_REPOSITORY/droidherd:latest
