name: Building, testing and assembling jar-file

on: [ push ]

env:
  DOCKER_REPOSITORY: ${{secrets.DOCKER_REPOSITORY}}

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Build, test and assemble jar
        run: ./gradlew build test bootJar
