name: Release Droidherd API

on:
  push:
    branches: [ "main", "build-docker" ]

#on:
#  release:
#    types: [created, workflow_dispatch]

jobs:
  publish-api-to-maven-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Check repository and tag
        run: scripts/release-env-check.sh

      - name: Set build version
        run: |
          VERSION = $(echo "$GITHUB_REF_NAME" | grep -Eo '[0-9]\.[0-9]+\.[0-9]+')
          echo "Evaluated version: $VERSION"
          [ -z "$VERSION" ] && exit 1
          echo "BUILD_VERSION=${VERSION}" >> $GITHUB_ENV

#      - uses: actions/checkout@v3
#
#      - name: Set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          cache: gradle
#
#      - name: Validate Gradle wrapper
#        uses: gradle/wrapper-validation-action@v1
#
#      - name: Retrieve the secret and decode it to a file
#        env:
#          GPG_KEY: ${{ secrets.GPG_KEY }}
#        run: echo "$GPG_KEY" | base64 --decode > /tmp/secring.gpg
#
#      - name: Retrieve the gradle.properties
#        env:
#          SIGN_OSSRH_GRADLE_PROPERTIES: ${{ secrets.SIGN_OSSRH_GRADLE_PROPERTIES }}
#        run: |
#          mkdir -p ~/.gradle
#          echo -en "$SIGN_OSSRH_GRADLE_PROPERTIES" > ~/.gradle/gradle.properties
#
#      - name: Execute Gradle publish
#        uses: gradle/gradle-build-action@v2
#        with:
#          arguments: :api:publish -Psigning.secretKeyRingFile=/tmp/secring.gpg
#        env:
#          MVN_RELEASE_REPOSITORY: https://oss.sonatype.org/service/local/staging/deploy/maven2/
#          MVN_LOGIN: ${{ secrets.NEXUS_LOGIN }}
#          MVN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
#
#      - name: Execute Gradle nexus staging release
#        uses: gradle/gradle-build-action@v2
#        with:
#          arguments: closeAndReleaseRepository
#        env:
#          MVN_RELEASE_REPOSITORY: https://oss.sonatype.org/service/local/
#          MVN_LOGIN: ${{ secrets.NEXUS_LOGIN }}
#          MVN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
